### ISSUE TITLE
Alignment of open boxes 

### ISSUE THREAD

**Issue by jonathanKingston** [GoogleChrome/css-triggers#13]
When opening a property name the following alignment issue occur.

Chrome stable(Version 48.0.2564.109 (64-bit) Ubuntu):
![selection_013](https://cloud.githubusercontent.com/assets/338988/13254164/1529016c-da38-11e5-98ca-73bcc40a6572.png)
Firefox stable(44.0.2 Ubuntu):
![selection_012](https://cloud.githubusercontent.com/assets/338988/13254168/200f25b6-da38-11e5-8a66-1ab225db8d72.png)
Firefox developer edition looks similar but scrolling is slightly less buggy.

**Comment by paullewis** [comment]
Thanks for the report. Would you be able to confirm that this is fixed?

**Comment by jonathanKingston** [comment]
@paullewis confirmed both browsers now behave. Thanks for the quick turn around :+1:
