### ISSUE TITLE
Cache-bust install handler requests

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/css-triggers#14]
Continuing the discussion from https://github.com/GoogleChrome/css-triggers/pull/11

Relying on ETags implies that you're not cache-busting your prefetching requests in your `install` handler. But you should be cache-busting those requests. Otherwise, what happens in the following scenario?

1. Alice visits your site at 10:00am, and `css-triggers-core.js` is precached in the service worker's `install` handler at that point.
2. You find a critical bug, update `css-triggers-core.js` at 10:05am, and push out a new `sw.js` with an updated `@VERSION@`.
3. Alice visits your site again at 10:10am, picks up the new `sw.js`, and the `install` handler is triggered again. The intended behavior is to pick up the updated `css-triggers-core.js` file, but because the browser cache of the old `css-triggers-core.js` doesn't expire until 11:00am, the out of date `css-triggers-core.js` is stored in the service worker cache.
4. The out of date `css-triggers-core.js` will now continue to be used well beyond the 1 hour worst-case lifetime implied by the `Cache-Control` headers, since the `fetch` handler uses a cache-first strategy.

If there's another update to `sw.js` made at some point in the future, the `install` handler will be triggered again, and at that point, the old `css-triggers-core.js` will finally be evicted. This might not happen for an extended period of time, though.

Things going wrong in between steps 2. and 3. implies that `sw.js` expires from the browser cache before the resources it references expire. Using an identical `Cache-Control` lifetime of less than [24 hours](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#update-algorithm) for *all* your resources mitigates this to some extent, but this is more than a theoretical possibility, and it leaves your users in an indefinite bad state.

**Comment by surma** [comment]
Ha, thanks for the detailed description, @jeffposnick.

I genuinely thought that our current solution would only grab the updated resources automagically. I may have stumbled upon a way to get the best from 2 worlds and actually reducing the amount of code in the service worker. I’ll whip something up and have you review it, if you don’t mind :)

**Comment by jakearchibald** [comment]
I stand by this https://twitter.com/jaffathecake/status/671698918686740480

**Comment by jakearchibald** [comment]
If you're unable to rely on the server doing the right thing, you can write your SW to verify stuff and fail the install if it isn't right, but the best answer is to fix the server, as this will benefit non-service-worker users too.

**Comment by jeffposnick** [comment]
The approach in https://github.com/GoogleChrome/css-triggers/pull/15 takes care of this. :+1:
