### ISSUE TITLE
Can't move scrollbar on Chrome (Linux?)

### ISSUE THREAD

**Issue by felixsanz** [GoogleChrome/css-triggers#16]
On Latest Chrome you can't use the scrollbar to move the page down, because the scrollbar is sitting behind the header and trying to click it just doesn't work.

At least on Linux.

**Comment by surma** [comment]
Kindly confirmed by @sgomes. It is also reproducible under OS X. 

I feel like this is a bug in Chrome rather than CSSTriggers fault, since we are scrolling on document level. @paullewis WDYT?

<img width="867" alt="screenshot 2016-03-07 11 04 36" src="https://cloud.githubusercontent.com/assets/234957/13567665/76160242-e454-11e5-989d-56bb69d62680.png">

**Comment by felixsanz** [comment]
I have also found this bug before in docker website

[pandoc @ hub.docker.com](https://hub.docker.com/r/jagregory/pandoc/)

Try to use the horizontal scrollbar of the `<pre><code>`. It just doesn't work again

**Comment by surma** [comment]
Actually, after taking a closer look, we are not scrolling document but on a `<section>` element. Thanks for issuing, @felixsanz. We’ll take a look :)

**Comment by felixsanz** [comment]
@surma 

About docker website, it actually works but press F5 and it won't work anymore. Weird

**Comment by paullewis** [comment]
We could `pointer-events: none` the header?

**Comment by surma** [comment]
My proposal: Turn the `.app-container`’s `padding-top` into a `margin-top`. Then the scroll bar will begin below the header, not under it.

If that doesn’t work, `pointer-events: none` fixes the issue.

**Comment by felixsanz** [comment]
My proposal: `.app-header { width: calc(100% - 14px) }`

:)

**Comment by paullewis** [comment]
@felixsanz The problem there is that you have a gap, where on Macs you don't necessarily have a scroll track. You do if a mouse is plugged in.

**Comment by felixsanz** [comment]
@paullewis But 14px is enough for all use cases.

**Comment by oldergod** [comment]
Might be too little a problem for anyone to want to fix it so I gave it a try.
