### ISSUE TITLE
Add more general forms of properties like border-radius

### ISSUE THREAD

**Issue by IchordeDionysos** [GoogleChrome/css-triggers#35]
Add `border-radius` property.

Triggers same steps like `border-bottom-left-radius`, `border-top-left-radius`, `border-top-right-radius` and `border-bottom-right-radius`

**Comment by IchordeDionysos** [comment]
Same for other properties like `border-color`, `border-style` and so on.

It's kinda confusing if you search for such a property and you don't find it.
And well when it's in all four cases the same, I think the 'parent' property should be listed as well.

I think most people would intuitively search for the more general property than for the side specific one.

**Comment by surma** [comment]
That’s because they are [CSS shorthands](https://developer.mozilla.org/en-US/docs/Web/CSS/Shorthand_properties). We only list primitive CSS properties. Maybe we’ll add shorthands eventually, but the test suite will need some fixing up to distinguish those from primitives.
