### ISSUE TITLE
Should scroll to top when you're searching.

### ISSUE THREAD

**Issue by camjc** [GoogleChrome/css-triggers#36]
Currently it looks broken if you're at the bottom of the page and start typing into the search box.
Awesome tool btw, thanks!

**Comment by davidpelayo** [comment]
It doesn't happen to me. It looks fine. What browser are you using @camjc?

**Comment by camjc** [comment]
Yep, looks fine now. Must have been fixed at some point. I would have been using Firefox 51 I guess, but not sure if it was a browser or a code issue. (Just tested on 52, and latest Chrome and looks perfect.)
