### ISSUE TITLE
Firebase Hosting: "Urgent DNS Migration Required"

### ISSUE THREAD

**Issue by sdtsui** [GoogleChrome/css-triggers#38]
[Live Site](https://csstriggers.com/) is currently down. 

![](https://puu.sh/uogYn/fe98bb5f5c.png)
Wasn't sure who to tell, I hope this is the right place! Please let me know if there's a better person to inform. :)
Thanks!

**Comment by surma** [comment]
I was about to say “works for me” until I realized Service Worker. lol.

Thanks for issuing! I’ll try to get it fixed ASAP.

**Comment by surma** [comment]
@paullewis I don’t have access to the domain records AFAIK, pls fix

**Comment by paullewis** [comment]
@surma @sdtsui Thanks ever so much for letting us know. I've updated DNS, just case of waiting for propagation now.

**Comment by surma** [comment]
Back to working for me! Gonna close this :) Thanks again @sdtsui

**Comment by sdtsui** [comment]
+1 same here. 
![](https://media.giphy.com/media/oaZncNXMel6yQ/giphy.gif)
