### ISSUE TITLE
Whas does the title mean?

### ISSUE THREAD

**Issue by NE-SmallTown** [GoogleChrome/css-triggers#39]
I notice that the "Change from default" and "Subsequent updates",but I can't understand well.Could anyone explain this?Thanks a lot.

And BTW,maybe make B,G,W,E be horizontal is better :smiley:

**Comment by oldergod** [comment]
### Change from default

In rendering pages, each browser applies its own styling rules to every elements that are not explicitly styled by the code, html or css. "Change from default" is when you change those browser _default_ styling rules to some others by defining explicitly some styles.

### Subsequent updates

Subsequent updates is when you update the style of an element whose style is already different from what the browser would have applied by default.

### Summary

```
no style → styleA = Change from default
styleA   → styleB = Subsequent updates
```

**Comment by NE-SmallTown** [comment]
Thanks!
