### ISSUE TITLE
Invalid certificate

### ISSUE THREAD

**Issue by Ryuno-Ki** [GoogleChrome/css-triggers#40]
When visiting https://csstriggers.com/ Firefox tells me, that the certificate is invalid.

The common name it is issued to is kitchenwallapp.com.
Please update the Let's Encrypt cert for it.

**Comment by surma** [comment]
Thanks for issuing! We are already aware and are working with Firebase to fix this. I'll keep you posted here.

**Comment by surma** [comment]
Got a new certificate and all is back up and running :)

**Comment by Ryuno-Ki** [comment]
That was fast! Thanks!
