### ISSUE TITLE
Website appears to be down

### ISSUE THREAD

**Issue by emyarod** [GoogleChrome/css-triggers#44]
I haven't been able to access https://csstriggers.com/ for a couple of days, but I'm not sure where else to report this issue:

![data-text-html chromewebdata 1](https://user-images.githubusercontent.com/8265238/27985911-290952fc-63c3-11e7-9080-8f61ac3b13d8.png)

**Comment by surma** [comment]
Eh, we migrated DNS providers and – for some reason – the records didn’t get carried over.

It’s fixed now! Might take up to a day or two to propagate to you :)

Thanks for issuing!
