### ISSUE TITLE
Empty information generates weird tooltip

### ISSUE THREAD

**Issue by TimvdLippe** [GoogleChrome/css-triggers#9]
![image](https://cloud.githubusercontent.com/assets/5948271/13226293/0df064dc-d991-11e5-8111-53e05087114f.png)

On for example `backface-visibility > subsequent updates`

**Comment by paullewis** [comment]
That _should_ be fixed now! Thanks!

**Comment by TimvdLippe** [comment]
Confirmed working, thanks for the quick fix!
